# Generated by Django 5.0.7 on 2024-07-24 21:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
    ]
