# Generated by Django 5.0.7 on 2024-07-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_doctor_first_name_doctor_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='nurse',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
