# Generated by Django 5.0.7 on 2024-07-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_nurse_first_name_nurse_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.TextField(verbose_name=''),
        ),
    ]
