# Generated by Django 5.0.7 on 2024-07-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_patient_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_sugar',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='details',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='vital_signs',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reason',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('blood_pressure_systolic', models.IntegerField()),
                ('blood_pressure_diastolic', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('blood_sugar', models.FloatField()),
                ('body_temperature', models.FloatField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.patient')),
            ],
        ),
    ]
