# Generated by Django 5.0.7 on 2024-07-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_patient_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.TextField(default=''),
        ),
    ]
