# Generated by Django 4.1.4 on 2024-08-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_patient_medications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='blood_sugar',
            field=models.IntegerField(),
        ),
    ]
