# Generated by Django 5.0.7 on 2024-08-03 17:44

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_vitalsigns_blood_sugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalinfo',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='vitalsigns',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
